import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { EmptyState } from "../components/EmptyState";
import { SectionCard } from "../components/SectionCard";
import { useIncident } from "../hooks/useIncidentStore";
import { getReportDownloadUrl, getReportMarkdown } from "../services/api";

export function ReportPage() {
  const { incidentId, reportMarkdown, setReportMarkdown, timelineData } = useIncident();
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!incidentId || reportMarkdown) {
      return;
    }

    const loadReport = async () => {
      setIsLoading(true);
      setError("");
      try {
        const markdown = await getReportMarkdown(incidentId);
        setReportMarkdown(markdown);
      } catch (loadError) {
        setError(loadError.message);
      } finally {
        setIsLoading(false);
      }
    };

    loadReport();
  }, [incidentId, reportMarkdown, setReportMarkdown]);

  if (!incidentId) {
    return (
      <EmptyState
        title="No report available"
        description="Reports are generated from uploaded incidents. Upload a log file first to create one."
        action={<Link to="/" className="rounded-full bg-sky-400 px-5 py-3 text-sm font-semibold text-slate-950">Go to Upload</Link>}
      />
    );
  }

  return (
    <div className="space-y-6">
      <SectionCard
        title="Incident Report"
        subtitle={timelineData?.originalFileName ? `Generated from ${timelineData.originalFileName}` : "Markdown export generated by the backend."}
        action={
          <a
            href={getReportDownloadUrl(incidentId)}
            className="rounded-full bg-sky-400 px-5 py-3 text-sm font-semibold text-slate-950 transition hover:bg-sky-300"
          >
            Download Markdown
          </a>
        }
      >
        {error ? <p className="text-sm text-rose-300">{error}</p> : null}
        {isLoading ? <p className="text-sm text-slate-400">Loading report...</p> : null}
        <pre className="overflow-x-auto rounded-[24px] border border-white/10 bg-slate-950/80 p-5 text-sm leading-7 text-slate-200 whitespace-pre-wrap">
          {reportMarkdown || "Report will appear here after the backend responds."}
        </pre>
      </SectionCard>
    </div>
  );
}
